server:
  port: 8181
  servlet:
    context-path: /springCloudConfig
spring:
  application:
    name: global-config-server
  cloud:
    config:
      server:
        git:
          uri: https://code.idc.hexun.com/tech_ywkf/global.git
          username: yanglin2016@staff.hexun.com
          password: gitpwd123
          search-paths: '{application}'
