server:
  port: 8181
  servlet:
    context-path: /springCloudConfig
spring:
  application:
    name: global-config-server
  cloud:
    config:
      server:
        git:
          uri: gitRepositoryUrl
          username: gitusername
          password: gitpassword
          search-paths: '{application}'
